# Generated by Django 2.2.12 on 2020-05-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='User',
            new_name='user',
        ),
    ]
